### ISSUE TITLE
Extension updated dialog keeps opening PayPal

### ISSUE THREAD

**Issue by TomyLobo** [opto/headerTools-lite-NG#2]
Wherever I click in that dialog, it opens PayPal.
The first time this happened, I thought I was being hacked or something.
Now it happened so often in a row that PayPal thinks I'm flooding and asks me for a CAPTCHA.

That's not a way to get people to donate, please remove the excessive PayPal linking.

**Comment by TomyLobo** [comment]
Looks like you pasted the PayPal code outside the braces :)

**Comment by opto** [comment]
sorry, that didn't happen here. Which dialog did you click into?

I have that in the installation greeting tab, with a donation button at the bottom and higher up an underlined link.
On Win 10, they don't autoactivate. If they really do elsewhere, that definitely is a nuisance that I did not intend.

Did you do a fresh install, on what OS and TB version? Or an upgrade from TB 60

Klaus

**Comment by TomyLobo** [comment]
I sent a PR. See https://github.com/opto/headerTools-lite-NG/pull/3
