### ISSUE TITLE
Why occupy 2 menu lines?

### ISSUE THREAD

**Issue by dumb0x** [opto/headerTools-lite-NG#6]
It's nice to have this functionality again, but why is it necessary to occupy 2 lines of the Message menu:

- Header Tools Lite
- Header Tools Improved

Both have the same submenu choices {Change header details | Edit full source | Options}; neither has a menu hotkey (the only menu items without a hotkey).  Could there be just a single menu item, with a hotkey?
Thanks.

**Comment by opto** [comment]
it seems you have 2 similiar addons installed. Header tools lite is the original addon from Paolo.
Header tools improved is a fork by Dillinger.
Both are currently maintained and Dillinger's code is identical with some changes for TB 68-TB 91.
When I saw it last, both addons were somewhat improved with respect to the original version of Paolo.
So it is your personal choice to verify what is improved where and which version you like more.

Hotkey: you can set the hotkeys in the options in header tools lite.
